name: Windows GitHub CI

on: [pull_request]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven repository caching
      uses: actions/cache@v1.1.0
      with:
        path: ~/.m2/repository
        key: gs-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gs-${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B clean install -Dall -T2 -Prelease --file src/pom.xml
    - name: Remove SNAPSHOT jars from repository
      run: |
        cmd --% /c for /f %i in ('dir /a:d /s /b %userprofile%\*SNAPSHOT*') do rd /s /q %i
